#!/bin/bash

#Variables for the screen brightness and keyboard backlight directory
usage() {
	printf "Usage: superpwrsaver [OPTION]..\n"
	printf " -v		Display version\n"
	printf " -s		Power saving mode\n"
	printf " -d		Set back to default\n"
}

# In the unlikely event of an error, it will notify the user
die() {
	printf "\033[1;37m%s: \e[0m%s\n" ERROR "$*"
	exit 1
}

# Display the version
version () {
	printf "\nsuperpwrsaver v0.0.2\n\n"
}

# Enable power saving mode
pwrsave () {
	echo 50 > /sys/class/backlight/*/brightness &
	echo 0 >  /sys/class/leds/*kbd_backlight/brightness &
	exit 0
}

# Disable powersaving mode
default () {
	echo 255 > /sys/class/backlight/*/brightness &
	echo 3 > /sys/class/leds/*kbd_backlight/brightness &
}

case "$1" in
	-v) version;;
	-s) pwrsave;;
	-d) default;;
	*) usage; exit 1;;
esac
